export const rows = [
  {
    id: 1,
    title: 'New User',
    condition_days: '1 to 30',
    point_reward: '5',
    description: '1 month of membership',
    avatar: 'badge1.png',
    contest_name: 'Tech contest',
    language_name: 'English',
    board: "CBSE",
    class: '10th'  ,
    stream: 'Science',
    created_date: '22/2/21',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 2,
    status: 2
  },
  {
    id: 2,
    title: 'Loyal User',
    condition_days: '31 to 365',
    point_reward: '10',
    description: '1 year of membership',
    avatar: 'badge2.png',
    contest_name: 'GK contest',
    language_name: 'Hindi',
    board: 'ICSE',
    class: '12th',
    stream: 'Arts',
    created_date: '13/6/22',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 1,
    status: 2
  },
  {
    id: 3,
    title: 'Faithful User',
    condition_days: '365 to 1000',
    point_reward: '15',
    description: 'Older then 1 year of membership',
    avatar: 'badge3.png',
    contest_name: 'Trivia quiz',
    language_name: 'Hindi',
    board: 'UP Board',
    class: '9th',
    stream: 'Science',
    created_date: '22/2/22',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 1,
    status: 2
  }
]