export const rows = [
  {
    id: 1,
    avatar: 'cbse-icon.png',
    contest_name: 'Tech contest',
    language_name: 'English',
    board: "CBSE",
    class: '10th'  ,
    stream: 'Science',
    start_date: '22/2/22',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 2,
    status: 2
  },
  {
    id: 2,
    avatar: 'icse-icon.jpg',
    contest_name: 'GK contest',
    language_name: 'Hindi',
    board: 'ICSE',
    class: '12th',
    stream: 'Arts',
    start_date: '22/2/22',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 1,
    status: 2
  },
  {
    id: 3,
    avatar: 'raj-board.jpg',
    contest_name: 'Trivia quiz',
    language_name: 'Hindi',
    board: 'UP Board',
    class: '9th',
    stream: 'Science',
    start_date: '22/2/22',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 1,
    status: 2
  },
  {
    id: 4,
    avatar: 'up-board-icon.jpg',
    contest_name: 'Maths contest',
    language_name: 'Rajasthani',
    board: 'Rajasthan Board',
    class: '11th',
    stream: 'Commerce',
    start_date: '22/2/22',
    end_date: '23/2/22',
    entry_points: 10,
    top_users: 5,
    participants: 10,
    questions:10,
    prize_status: 1,
    status: 1
  }
]