export const rows = [
  {
    id: 1,
    avatar: '3.png',
    full_name: 'Akshar Patel',
    total_points: '15',
    spent_points: '0',
    remaining_points: '15',
    email: 'yogesh12@gmail.com',
    phone: '12345678',
    language_name: 'English',
    board: "CBSE",
    class: '10th',
    stream: 'Science',
    status: 1
  },
  {
    id: 2,
    avatar: '1.png',
    full_name: 'Rajesh Bhatt',
    total_points: '15',
    spent_points: '0',
    remaining_points: '15',
    email: 'rajesh12@gmail.com',
    phone: '12345678',
    language_name: 'Hindi',
    board: 'ICSE',
    class: '12th',
    stream: 'Arts',
    status: 2
  },
  {
    id: 3,
    avatar: '2.png',
    full_name: 'Mukesh Raja',
    total_points: '15',
    spent_points: '0',
    remaining_points: '15',
    email: 'mukesh12@gmail.com',
    phone: '12345678',
    language_name: 'Hindi',
    board: 'UP Board',
    class: '9th',
    stream: 'Science',
    status: 2
  },
  {
    id: 4,
    avatar: '8.png',
    full_name: 'Pooja Kumari',
    total_points: '15',
    spent_points: '0',
    remaining_points: '15',
    email: 'pooja12@gmail.com',
    phone: '12345678',
    language_name: 'Rajasthani',
    board: 'Rajasthan Board',
    class: '11th',
    stream: 'Commerce',
    region: 'Rajasthan',
    status: 1
  }
]